"""
Data loader for the Graph Traversal Engine.

Reads pre-computed data from disk and assembles ContextGraph and GraphFamily
objects. All heavy computation (DR bridge, message passing, TDA) was done
offline -- this module only reads and indexes.

Data sources (wave-aware):
  - data/tda/allwave/matrices/W{n}/   (weight matrices + manifest per wave)
  - data/tda/matrices/                 (W7 legacy fallback)
  - data/gte/W{n}/fingerprints/        (per-country SES fingerprints per wave)
  - data/gte/fingerprints/             (W7 legacy fallback)
  - data/gte/W{n}/camps/               (per-country bipartitions per wave)
  - data/gte/camps/                    (W7 legacy fallback)
  - data/gte/construct_descriptions.json
  - data/tda/message_passing/W{n}/     (BP, PPR, spectral per wave)
  - data/tda/message_passing/          (W7 legacy fallback)
  - data/tda/spectral/                 (spectral distances -- W7 only)
  - data/tda/floyd_warshall/           (mediator scores -- W7 only)
  - data/tda/allwave/convergence/      (Fiedler heatmap, mediator stability)
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

from graph_traversal_engine.context import (
    WAVE_YEARS,
    CampAssignment,
    Context,
    ContextGraph,
    Fingerprint,
    GraphFamily,
)

# -- Default paths (relative to project root) ----------------------------------
# These resolve whether running from project root or from tests.

ROOT = Path(__file__).resolve().parents[1]

# navegador_data repo (sibling or child -- try both common locations)
_ND_CANDIDATES = [
    ROOT / "navegador_data",                     # child of project
    ROOT.parent / "navegador_data",              # sibling of project
]
NAVEGADOR_DATA = next((p for p in _ND_CANDIDATES if p.exists()), _ND_CANDIDATES[0])

# Wave-aware paths (primary)
ALLWAVE_MATRIX_DIR = NAVEGADOR_DATA / "data" / "tda" / "allwave" / "matrices"
ALLWAVE_FP_DIR = NAVEGADOR_DATA / "data" / "gte"
ALLWAVE_CAMP_DIR = NAVEGADOR_DATA / "data" / "gte"
ALLWAVE_MP_DIR = NAVEGADOR_DATA / "data" / "tda" / "message_passing"

# Legacy W7 flat paths (fallback)
MATRIX_DIR = NAVEGADOR_DATA / "data" / "tda" / "matrices"
FP_DIR = NAVEGADOR_DATA / "data" / "gte" / "fingerprints"
CAMP_DIR = NAVEGADOR_DATA / "data" / "gte" / "camps"
MP_DIR = NAVEGADOR_DATA / "data" / "tda" / "message_passing"

# Cross-context data (wave-independent)
CORPUS_PATH = NAVEGADOR_DATA / "data" / "gte" / "construct_descriptions.json"
SPECTRAL_DIR = NAVEGADOR_DATA / "data" / "tda" / "spectral"
FW_DIR = NAVEGADOR_DATA / "data" / "tda" / "floyd_warshall"
CONVERGENCE_DIR = NAVEGADOR_DATA / "data" / "tda" / "allwave" / "convergence"


# -- Path resolution helpers ---------------------------------------------------

def _matrix_dir_for_wave(wave: int) -> Path:
    """Resolve weight matrix directory: allwave/matrices/W{n}/ or legacy."""
    allwave = ALLWAVE_MATRIX_DIR / f"W{wave}"
    if allwave.exists():
        return allwave
    if wave == 7 and MATRIX_DIR.exists():
        return MATRIX_DIR
    return allwave  # Will produce FileNotFoundError downstream


def _fp_dir_for_wave(wave: int) -> Path:
    """Resolve fingerprint directory: gte/W{n}/fingerprints/ or legacy.

    Also checks the main repo's data/results/wvs_kg/W{n}/ for per-country
    _fp.json files (generated by build_wvs_kg_per_wave.py).
    """
    allwave = ALLWAVE_FP_DIR / f"W{wave}" / "fingerprints"
    if allwave.exists():
        return allwave
    if wave == 7 and FP_DIR.exists():
        return FP_DIR
    # Fallback: main repo wvs_kg per-wave directory (has {COUNTRY}_fp.json)
    wvs_kg = ROOT / "data" / "results" / "wvs_kg" / f"W{wave}"
    if wvs_kg.exists():
        return wvs_kg
    return allwave


def _camp_dir_for_wave(wave: int) -> Path:
    """Resolve camp directory: gte/W{n}/camps/ or legacy."""
    allwave = ALLWAVE_CAMP_DIR / f"W{wave}" / "camps"
    if allwave.exists():
        return allwave
    if wave == 7 and CAMP_DIR.exists():
        return CAMP_DIR
    return allwave


def _mp_dir_for_wave(wave: int) -> Path:
    """Resolve message passing directory: W{n}/ subdir or legacy flat dir."""
    allwave = ALLWAVE_MP_DIR / f"W{wave}"
    if allwave.exists():
        return allwave
    if wave == 7 and MP_DIR.exists():
        return MP_DIR
    return allwave


# -- Manifest Loading ----------------------------------------------------------

def load_manifest(wave: int = 7) -> dict:
    """Load the TDA manifest for a specific wave."""
    matrix_dir = _matrix_dir_for_wave(wave)
    path = matrix_dir / "manifest.json"
    with open(path) as f:
        return json.load(f)


# -- Fingerprint Loading -------------------------------------------------------

def _load_fingerprints(
    country: str, construct_index: list[str], wave: int = 7,
) -> dict[str, Fingerprint]:
    """
    Load per-construct fingerprints for one country.

    Fingerprint JSON keys come in multiple formats across data sources:
      - Bare names: "gender_role_traditionalism"  (legacy gte/fingerprints/)
      - Domain-prefixed: "WVS_D|gender_role_traditionalism"  (wvs_kg/)
      - Domain-suffixed: "gender_role_traditionalism|WVS_D"  (manifest format)
    We match by normalizing all to the manifest format (name|WVS_X).
    """
    fp_dir = _fp_dir_for_wave(wave)

    # Try {COUNTRY}.json first, then {COUNTRY}_fp.json (wvs_kg format)
    fp_path = fp_dir / f"{country}.json"
    if not fp_path.exists():
        fp_path = fp_dir / f"{country}_fp.json"
    if not fp_path.exists():
        return {}

    with open(fp_path) as f:
        data = json.load(f)

    raw = data.get("constructs", {})
    fingerprints = {}

    # Build lookup from multiple key forms to canonical construct_index key.
    # Manifest uses "name|WVS_X" (domain-suffixed).
    key_lookup = {}
    for full_key in construct_index:
        key_lookup[full_key] = full_key
        if "|" in full_key:
            parts = full_key.split("|")
            bare_name = parts[0]
            domain = parts[1] if len(parts) > 1 else ""
            key_lookup[bare_name] = full_key
            # Reversed form: "WVS_X|name"
            key_lookup[f"{domain}|{bare_name}"] = full_key

    for raw_key, fp_data in raw.items():
        full_key = key_lookup.get(raw_key)
        if full_key is None:
            continue

        def _clean(v):
            if v is None:
                return 0.0
            try:
                return 0.0 if math.isnan(v) else v
            except (TypeError, ValueError):
                return 0.0

        rho_vals = {
            dim: _clean(fp_data.get(f"rho_{dim}"))
            for dim in ["escol", "Tam_loc", "sexo", "edad"]
        }
        raw_mag = fp_data.get("ses_magnitude", 0.0)
        ses_mag = _clean(raw_mag)

        fingerprints[full_key] = Fingerprint(
            rho_escol=rho_vals["escol"],
            rho_Tam_loc=rho_vals["Tam_loc"],
            rho_sexo=rho_vals["sexo"],
            rho_edad=rho_vals["edad"],
            ses_magnitude=ses_mag,
            dominant_dim=fp_data.get("dominant_dim") or "",
            n_valid=fp_data.get("n_valid", 0),
        )

    return fingerprints


# -- Camp Loading --------------------------------------------------------------

def _load_camps(
    country: str, wave: int = 7,
) -> tuple[dict[str, CampAssignment], float, float]:
    """Load bipartition data for one country. Returns (camps, fiedler, balance)."""
    camp_dir = _camp_dir_for_wave(wave)
    camp_path = camp_dir / f"{country}.json"
    if not camp_path.exists():
        return {}, 0.0, 0.0

    with open(camp_path) as f:
        data = json.load(f)

    camps = {}
    for key, cdata in data.get("constructs", {}).items():
        camps[key] = CampAssignment(
            camp_id=cdata["camp_id"],
            camp_name=cdata["camp_name"],
            confidence=cdata["confidence"],
            frustrated_ratio=cdata["frustrated_ratio"],
            n_triangles=cdata["n_triangles"],
            is_boundary=cdata["is_boundary"],
        )

    return camps, data.get("fiedler_value", 0.0), data.get("structural_balance", 0.0)


# -- Weight Matrix Loading -----------------------------------------------------

def _load_weight_matrix(
    country: str, construct_index: list[str], wave: int = 7,
) -> tuple[np.ndarray, int]:
    """
    Load weight matrix CSV and align to construct_index order.

    Returns (n x n matrix aligned to construct_index, n_significant_edges).
    """
    matrix_dir = _matrix_dir_for_wave(wave)
    csv_path = matrix_dir / f"{country}.csv"
    n = len(construct_index)

    if not csv_path.exists():
        return np.full((n, n), np.nan), 0

    df = pd.read_csv(csv_path, index_col=0)
    W = np.full((n, n), np.nan)

    csv_labels = list(df.columns)
    csv_to_idx = {}
    for ci, ck in enumerate(construct_index):
        if ck in csv_labels:
            csv_to_idx[ck] = ci

    n_sig = 0
    for ck_i, ci_i in csv_to_idx.items():
        for ck_j, ci_j in csv_to_idx.items():
            if ci_i == ci_j:
                continue
            val = df.loc[ck_i, ck_j] if ck_i in df.index and ck_j in df.columns else np.nan
            if pd.notna(val):
                W[ci_i, ci_j] = float(val)
                if ci_i < ci_j:
                    n_sig += 1

    return W, n_sig


# -- Message Passing Loading (Phase 2 -- optional) ----------------------------

def _load_bp(country: str, wave: int = 7) -> Optional[np.ndarray]:
    """Load BP lift matrix for a country. Returns n x n array or None."""
    mp_dir = _mp_dir_for_wave(wave)
    path = mp_dir / f"{country}_bp.json"
    if not path.exists():
        return None
    with open(path) as f:
        data = json.load(f)
    lift = data.get("lift_matrix")
    if lift is None:
        return None
    return np.array(lift)


def _load_ppr(
    country: str, wave: int = 7,
) -> tuple[Optional[dict], Optional[dict]]:
    """Load PPR hub and sink scores for a country."""
    mp_dir = _mp_dir_for_wave(wave)
    path = mp_dir / f"{country}_ppr.json"
    if not path.exists():
        return None, None
    with open(path) as f:
        data = json.load(f)
    return data.get("hub_scores"), data.get("sink_scores")


def _load_spectral_mp(
    country: str, wave: int = 7,
) -> tuple[Optional[np.ndarray], Optional[dict]]:
    """Load spectral eigenvalues and Fiedler partition."""
    mp_dir = _mp_dir_for_wave(wave)
    path = mp_dir / f"{country}_spectral.json"
    if not path.exists():
        return None, None
    with open(path) as f:
        data = json.load(f)
    eig_summary = data.get("eigenvalue_summary", {})
    eigenvalues = eig_summary.get("all_eigenvalues")
    fiedler_part = data.get("fiedler_partition")
    return (np.array(eigenvalues) if eigenvalues else None), fiedler_part


# -- TDA Feature Loading (Phase 3 -- optional) --------------------------------

def _load_spectral_distances(
    spectral_dir: Path = SPECTRAL_DIR,
) -> tuple[Optional[np.ndarray], Optional[list[str]]]:
    """Load pairwise spectral distance matrix between countries."""
    path = spectral_dir / "spectral_distance_matrix.csv"
    if not path.exists():
        return None, None
    df = pd.read_csv(path, index_col=0)
    return df.values.astype(float), list(df.index)


def _load_mediator_scores(
    country: str, fw_dir: Path = FW_DIR
) -> Optional[dict]:
    """Load Floyd-Warshall mediator scores for a country."""
    path = fw_dir / "mediator_scores.json"
    if not path.exists():
        return None
    with open(path) as f:
        data = json.load(f)
    return data.get(country)


def _load_fiedler_heatmap(
    convergence_dir: Path = CONVERGENCE_DIR,
) -> Optional[dict]:
    """Load Fiedler heatmap (country x wave)."""
    path = convergence_dir / "fiedler_heatmap.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path, index_col=0)
    result = {}
    for country in df.index:
        result[country] = {}
        for col in df.columns:
            val = df.loc[country, col]
            if pd.notna(val):
                result[country][int(col)] = float(val)
    return result


def _load_mediator_stability(
    convergence_dir: Path = CONVERGENCE_DIR,
) -> Optional[dict]:
    """Load mediator stability data."""
    path = convergence_dir / "mediator_stability.json"
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


# -- Construct Descriptions ----------------------------------------------------

def _load_construct_descriptions(
    path: Path = CORPUS_PATH,
) -> Optional[dict]:
    """Load construct description corpus."""
    if not path.exists():
        return None
    with open(path) as f:
        data = json.load(f)
    return data.get("constructs", data)


# -- Main Assembly Functions ---------------------------------------------------

def load_context_graph(
    country: str,
    wave: int = 7,
    manifest: Optional[dict] = None,
    load_mp: bool = True,
) -> ContextGraph:
    """
    Load a complete ContextGraph for one (country, wave) context.

    Args:
        country: ISO Alpha-3 code
        wave: WVS wave number (3-7)
        manifest: Pre-loaded manifest dict (avoids re-reading)
        load_mp: Whether to load message passing outputs
    """
    if manifest is None:
        manifest = load_manifest(wave)

    construct_index = manifest["construct_index"]
    country_zone = manifest.get("country_zone", {})

    # Core data
    W, n_sig = _load_weight_matrix(country, construct_index, wave)
    fingerprints = _load_fingerprints(country, construct_index, wave)
    camps_raw, fiedler, balance = _load_camps(country, wave)

    # Map camp keys to construct_index
    camps = {}
    for key in construct_index:
        if key in camps_raw:
            camps[key] = camps_raw[key]

    ctx = Context(
        country=country,
        wave=wave,
        year=WAVE_YEARS.get(wave, 0),
        zone=country_zone.get(country, ""),
        n_constructs=len(construct_index),
    )

    graph = ContextGraph(
        context=ctx,
        constructs=construct_index,
        weight_matrix=W,
        fingerprints=fingerprints,
        camps=camps,
        fiedler_value=fiedler,
        structural_balance=balance,
        n_significant_edges=n_sig,
    )

    # Load pre-computed message passing outputs (any wave)
    if load_mp:
        graph.bp_lift_matrix = _load_bp(country, wave)
        graph.ppr_hub_scores, graph.ppr_sink_scores = _load_ppr(country, wave)
        graph.spectral_eigenvalues, graph.spectral_fiedler_partition = (
            _load_spectral_mp(country, wave)
        )

    # TDA features (W7 only for now)
    if wave == 7:
        mediator_data = _load_mediator_scores(country)
        if mediator_data:
            graph.top_mediator = mediator_data.get("most_common")

    return graph


def load_graph_family(
    waves: list[int] | None = None,
    countries: list[str] | None = None,
    load_mp: bool = True,
) -> GraphFamily:
    """
    Load the full graph family: all requested contexts + cross-context data.

    Args:
        waves: Which waves to load (default: [7])
        countries: Which countries to load (default: all in W7 manifest)
        load_mp: Whether to load message passing outputs
    """
    if waves is None:
        waves = [7]

    # Load per-wave manifests and build a global construct index (union)
    manifests = {}
    all_constructs = set()
    for wave in waves:
        try:
            m = load_manifest(wave)
            manifests[wave] = m
            all_constructs.update(m["construct_index"])
        except FileNotFoundError:
            continue

    if not manifests:
        raise FileNotFoundError(
            f"No manifests found for waves {waves}. "
            f"Check that allwave matrices exist in {ALLWAVE_MATRIX_DIR}"
        )

    # Use W7 construct index as the canonical order (superset)
    if 7 in manifests:
        construct_index = manifests[7]["construct_index"]
    else:
        construct_index = sorted(all_constructs)

    if countries is None:
        # Default to W7 countries (largest set)
        ref = manifests.get(7, next(iter(manifests.values())))
        countries = ref.get("countries", [])

    # Load context graphs
    contexts = {}
    for wave in waves:
        if wave not in manifests:
            continue
        manifest = manifests[wave]
        wave_countries = manifest.get("countries", [])
        for country in countries:
            if country not in wave_countries:
                continue
            graph = load_context_graph(
                country, wave, manifest=manifest, load_mp=load_mp
            )
            contexts[(country, wave)] = graph

    # Cross-context data
    spectral_dists, spectral_countries = _load_spectral_distances()
    fiedler_heatmap = _load_fiedler_heatmap()
    mediator_stability = _load_mediator_stability()
    descriptions = _load_construct_descriptions()

    # Merge zones from all manifests
    country_zones = {}
    for m in manifests.values():
        country_zones.update(m.get("country_zone", {}))

    return GraphFamily(
        contexts=contexts,
        construct_index=construct_index,
        spectral_distances=spectral_dists,
        spectral_countries=spectral_countries,
        fiedler_heatmap=fiedler_heatmap,
        mediator_stability=mediator_stability,
        country_zones=country_zones,
        construct_descriptions=descriptions,
    )
